---
title: "&nbsp;"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      dev = "svg",
                      results = "asis")

box::use(R/util[render_image_html])

box::use(
  leaflet[leaflet, addProviderTiles, providers, addMarkers, popupOptions, labelOptions, icons, makeIcon],
  htmltools[HTML])
```


#### **Bristar Intl Trading Ltd.**
**Address**
12440 Bridgeport Road, Richmond, B.C., V6V 1J5

**Telephone**
+1-604-244-7234

**Fax**
+1-604-273-5820

**Email**
admin@bristar.ca

```{r map, out.width="50%"}
my_icon <- icons(iconUrl = "images/logo/logo-no-background.svg",
                 iconWidth = 100,
                 iconHeight = 65)

popup_text <- paste(sep = "<br/>",
  "<b><a href='http://www.bristar.ca'>Bristar Intl Trading Ltd.</a></b>",
  "12440 Bridgeport Road",
  "Richmond, B.C. V6V 1J5",
  "Canada"
)

leaflet() |>
  addProviderTiles(providers$Stamen.TonerLite) |>
  addMarkers(
    lng = -123.08595,
    lat = 49.19190,
    icon = my_icon,
    label = HTML(popup_text),
    options = popupOptions(closeButton = FALSE),
    labelOptions = labelOptions(noHide = TRUE,
                                direction = "top",
                                offset = c(0, -20))
  )
```

